= Mockito from Scratch

[partintro]
--
Mockito is a framework for creating mock objects in Java. When used in unit
tests, Mockito makes it significantly easier to isolate the code that you
actually want to test from everything else that could possibly break. This
guide is written for developers who are familiar with Java, and who can write
a simple JUnit test case, and who want to know how to take their unit testing
to the next level.

Before you get started learning about how to you use Mockito, add this to your
`pom.xml`:

[source, xml]
.In the dependencies section of your pom.xml file
----
<dependency>
  <groupId>org.mockito</groupId>
  <artifactId>mockito-all</artifactId>
  <version>1.10.19</version>
  <scope>test</scope>
</dependency>
----
--

== Introduction to Mocks

A mock object created by Mockito extends a class and overrides every method to
do nothing. Imagine if you had an object like this:

[source, java]
----
class MyObject {
  public int getValue() {
    return db.loadValue();
  }
  
  public void setValue(int nextValue) {
    complicatedValidation(nextValue);
    db.saveValue(nextValue);
  }
  
  public MyBean getBean() {
    MyBean bean = MyBean.staticFactoryThatCallsService();
    bean.longRunningLoad();
    return bean;
  }
  
  public void setBean(MyBean nextBean) {
    db.saveValue(nextBean);
  }
}
----

And imagine that another class of yours used this object. You don’t want to
worry about what kind of plumbing this object has. You just want something
to pass around in the class that you actually care about. To create a mock
of this object, you call the method `Mockito.mock()`:

[source, java]
----
import static org.mockito.Mockito.mock;

class OtherObjectTest {
  MyObject theMock = mock(MyObject.class);
}
----

When given a `Class` object, the `Mockito.mock()` method returns a mock of
that type.

NOTE: There are several ways to create mock objects, and some of them buy
you a lot more power and flexibility. They need some Mockito features that
we haven’t covered yet. All those other strategies end up calling
`Mockito.mock()`, anyway.

For Mockito, "`absolutely nothing`" means it creates a subclass like this:

[source, java]
----
class MyObjectMock extends MyObject {
  public int getValue() {
    return 0;
  }
  
  public void setValue(int nextValue) {
    // blank
  }
  
  public MyBean getBean() {
    return null;
  }
  
  public void setBean(MyBean nextBean) {
    // blank
  }
}
----

That means that calling `setX()` methods on a mock object won't affect future
calls to `getX()`, and you better be careful if your code calls `getBean()`
and then does something with the result. Every method does as little as
possible by returning an appropriate "`empty`" value.

.Empty values for each return type
[horizontal]
Numeric primitives:: Returns zero
`char` primitive:: Returns the null byte (`\0`)
`String` objects:: Returns an empty string (`""`)
`Collection` classes:: Returns an empty collection
Any other object:: Returns `null`

On their own, mocks are sort of useful, but those `null` values can cause
trouble. The other half of this puzzle is the static method `Mockito.when()`.
We cover that method in the next section.

== Making mocks return what you want

The `Mockito.mock()` method gives you a dummy object. You can use it to avoid
complicated constructors, long-running methods, etc. In general, use it any
time that you want to decouple another class from your test subject.

The problem, of course, is that an object that does nothing isn’t useful. We
need a way to control our test subject's behavor, which requires input &
output to & from these objects. To tell your mock objects how to behave, you
use the static method `Mockito.when()`.

=== "`When,`" Then What?

Mockito's `when()` returns an object that, in itself, we don't care about. We
only care about the method that we chain on to `when()`, called `thenReturn()`.
The methods `when().thenReturn()` form the basis of the commands to your mock
object. Here's a full example:

[source, java]
----
@Test
public void testStubbing() {

  MyObject myMock = mock(MyObject.class);
  when(myMock.getValue()).thenReturn(42);
  
  assertEquals(42, myMock.getValue())
}
----

I'm sure alarm bells are probably going off in your head. Yes, the syntax is
unusual. But, this is the most concise way to tell our mock how to behave. To
grasp this command, you have to let go of a little bit of your Java knowledge
for just a minute. Don't think of `myMock.getValue()` as returning a value.
Think of it as _identifying the method that you want to change_.

IMPORTANT: The `when(mock.method()).thenReturn(value)` syntax is the
trickiest thing to learn when you are learning Mockito. The argument to `when()`
is the method call that you're changing. The `thenReturn(value)` tells the
mock what you want that method to do.

The statement `when(myMock.getValue()).thenReturn(expectedValue)` instructs
`myMock` to return `expectedValue` when something calls `getValue()`. That
lasts *for the life of the mock*. That means that calling `setValue()` will
*not* change the result of `getValue()`.

CAUTION: Mocking an object breaks the contract of getters and setters. Setters
will not change any value, and getters will always return what you tell them to.
If you're ever calling a setter on a mock object, it is most likely a mistake.

[source, java]
----
@Test
public void thisTestPasses() {

  MyObject myMock = mock(MyObject.class);
  when(myMock.getValue()).thenReturn(42);

  // The mock will now behave as instructed
  assertTrue(myMock.getValue() == 42);
  
  // This does nothing, since myMock is a mock
  myMock.setValue(13);
  
  // getValue still returns 42!
  assertTrue(myMock.getValue() == 42);
}
----


== Anatomy of a JUnit Test Using Mockito

It is worthwhile to write your tests so that you can completely control your
class through its mocks. The mocks are clients of your code just as much as
the rest of your application. If you can replace collaborators with mocks,
then you can replace them with other implementations, too.

The following listing shows a unit test that uses Mockito annotations to
create mocks.

[source, java]
.A test class using Mockito annotations
----
include::listings/AnnotationsAnatomy.java[]
----
<1> JUnit's `@Rule` annotation lets us use plugins, like Mockito. This will
call Mockito's setup methods.
<2> This makes Mockito instantiate that object and inject our mocks into it.
<3> Mockito will create a mock object of this type, even if it's an interface.
<4> We just covered this. Note that it is legal to ask one mock to return
another.

=== Mockito's JUnit rule

JUnit's `Rule` system is a system for plugins. For every `@Rule` JUnit will
call methods on that object before and after every test. The `MockitoJUnit`
rule mocks everything `@Mock` object, then injects them into your
`@InjectMocks` object. It helps take a lot of repetition out of setting up
tests.

NOTE: You must declare all JUnit rules as `public`.

=== Injecting Mocks

The `@InjectMocks` annotation hides a lot of complexity. It instantiates
a real (non-mock) instance of that type, then it tries to inject all the
`@Mock` objects. Therein lies the complexity. How do you inject mock
objects into the class you’re testing?

Mockito tries three strategies of injection:

 . Constructor injection
 . Setter injection
 . Reflection
 
It evaluates the class's constructor, setters, and fields, in that order.
Then, it picks the first one that will work for all declared mocks.

CAUTION: Mockito does not provide any feedback on which strategy it picked, or
if it failed to mock anything. Be conscious of what strategy you want Mockito
use, and make sure that your class allows it.

==== Constructor Injection

Mockito first checks if you have a constructor with arguments matching your
`@Mock` types. It will try to use the biggest public constructor available, and then
it will construct your class by using that constructor, passing in your mocks
by matching types. If your have multiple arguments of the same type, you
can name your mocks. See the Javadoc on Mockito's `@InjectMock` annotation.
If the biggest constructor has some arguments that you don't have types for,
Mockito will pass `null` for those values.

TIP: This strategy is my favorite, because it lets you declare your
dependencies as `final` fields within your class. If you have many `final`
fields, and one of your constructors doesn't initialize one, then you will get
a compilation error. I like letting the compiler work in my favor.

[source, java]
.A class that uses constructor injection
----
include::listings/ConstructorInjection.java[]
----

If your class does not have a constructor that accepts any of the mocks you've
made, Mockito will try setter injection next.

==== Setter Injection

If you have methods with the name like `setX()` that accept the types of mocks
you've created, Mockito will instantiate your object using the default
constructor, then it will call those setters, passing in your mocks. This is
definitely the most straightforward, and it's very likely that your existing
code has setters for its dependencies, since that's the Java bean style.

If your class does not have setters for some of your mocks, 
